language: generic
sudo: false
git:
  depth: 1

addons:
  apt:
    packages:
      - php5-cli
      - python3
      - python3-pip
      - openjdk-8-jre-headless
  ssh_known_hosts: orgplace.tk

install:
- pip install --user Pygments
- nvm install --lts
- npm i -g less less-plugin-autoprefix less-plugin-clean-css less-plugin-glob less-plugin-csscomb globby html-minifier
- cd js-gcl && npm i && cd ..

before_script:
- export PATH=$HOME/.local/bin:$PATH

script:
- make -j2
- 'find dist -type f -name "*.d" -exec rm {} \;'
- 'find dist \( -name "*.html" -o -name "*.css" -o -name "*.js" \) -type f -exec sh -c "gzip -c {} > {}.gz" \;'

before_deploy:
- openssl aes-256-cbc -K $encrypted_a0ddd763164c_key -iv $encrypted_a0ddd763164c_iv -in deploy_ssh_key.enc -out /tmp/deploy_ssh_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_ssh_key
- ssh-add /tmp/deploy_ssh_key

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -azvr --delete --chmod=D755,F644 dist/ orgplace@orgplace.tk:/srv/master/_/ui/
  on:
    branch: master
