language: generic
sudo: false
dist: xenial
git:
  depth: 1

addons:
  apt:
    packages:
    - php-cli
    - python3
    - python3-pip

install:
- pip install --user Pygments
- nvm install --lts
- npm i -g less less-plugin-autoprefix less-plugin-clean-css less-plugin-glob less-plugin-csscomb html-minifier html-validator-cli

before_script:
- export PATH=$HOME/.local/bin:$PATH

script:
- make -j2
