image: utisam/docker-static-web

pipelines:
  default:
    - step:
        script:
          - 'make'
          - 'find dist -name "*.html" -print0 | xargs --verbose -0 -n1 html-validator --verbose --file'
  branches:
    master:
      - step:
          script:
            - 'make'
            - 'find dist -name "*.html" -print0 | xargs --verbose -0 -n1 html-validator --verbose --file'
            - 'find dist -type f -name "*.d" -exec rm {} \;'
            - 'find dist -type f -exec sh -c "gzip -c {} > {}.gz" \;'
            - 'find dist \( -name "*.html" -o -name "*.css" -o -name "*.js" \) -type f -exec sh -c "gzip -c {} > {}.gz" \;'
            - 'rsync -azvr --delete --chmod=D755,F644 dist/ orgplace@orgplace.f5.si:/srv/master/_/ui/ --exclude "*.d"'
