image: utisam/docker-static-web

pipelines:
  default:
    - step:
        script:
          - 'make'
          - 'find dist -name "*.html" -print0 | xargs --verbose -0 -n1 html-validator --verbose --file'
  branches:
    master:
      - step:
          script:
            - 'make'
            - 'find dist -name "*.html" -print0 | xargs --verbose -0 -n1 html-validator --verbose --file'
      - step:
          image: atlassian/default-image:latest
          script:
            - 'rsync -azvr --delete dist/ orgplace@orgplace.f5.si:/srv/master/_ui/'
